version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres-shipment
    environment:
      POSTGRES_DB: shipmentdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5439:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

